/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_alternativetags.h"
#include "bar_dwmblocks.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_statusbutton.h"
#include "bar_statuscmd.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_systray.h"
#include "bar_layoutmenu.h"

/* Other patches */
#include "alttab.h"
#include "attachx.h"
#include "cfacts.h"
#include "cyclelayouts.h"
#include "distributetags.h"
#include "killunsel.h"
#include "movestack.h"
#include "nomodbuttons.h"
#include "pertag.h"
#include "placemouse.h"
#include "riodraw.h"
#include "roundedcorners.h"
#include "renamed_scratchpads.h"
#include "seamless_restart.h"
#include "shift.h"
#include "shifttag.h"
#include "shiftview.h"
#include "sticky.h"
#include "swallow.h"
#include "tagallmon.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
#include "zoomswap.h"
#include "xrdb.h"
/* Layouts */
#include "layout_columns.h"
#include "layout_deck.h"
#include "layout_fibonacci.h"
#include "layout_gapplessgrid.h"
#include "layout_monocle.h"
#include "layout_tile.h"

