/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_alternativetags.c"
#include "bar_dwmblocks.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_statusbutton.c"
#include "bar_statuscmd.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_systray.c"
#include "bar_layoutmenu.c"

/* Other patches */
#include "alttab.c"
#include "attachx.c"
#include "cfacts.c"
#include "cyclelayouts.c"
#include "distributetags.c"
#include "killunsel.c"
#include "movestack.c"
#include "nomodbuttons.c"
#include "pertag.c"
#include "placemouse.c"
#include "riodraw.c"
#include "roundedcorners.c"
#include "renamed_scratchpads.c"
#include "shift.c"
#include "shifttag.c"
#include "shiftview.c"
#include "sticky.c"
#include "swallow.c"
#include "tagallmon.c"
#include "togglefullscreen.c"
#include "vanitygaps.c"
#include "zoomswap.c"
#include "xrdb.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_columns.c"
#include "layout_deck.c"
#include "layout_fibonacci.c"
#include "layout_gapplessgrid.c"
#include "layout_monocle.c"
#include "layout_tile.c"

