/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_alternativetags.c"
#include "bar_dwmblocks.c"
#include "bar_ewmhtags.c"
#include "combo.c"
#include "bar_launcher.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_statusbutton.c"
#include "bar_statuscmd.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_systray.c"

/* Other patches */
#include "alttab.c"
#include "attachx.c"
#include "cfacts.c"
#include "cool_autostart.c"
#include "cyclelayouts.c"
#include "decorationhints.c"
#include "distributetags.c"
#include "focusadjacenttag.c"
#include "focusurgent.c"
#include "ipc.c"
#ifdef VERSION
#include "ipc/IPCClient.c"
#include "ipc/yajl_dumps.c"
#include "ipc/ipc.c"
#include "ipc/util.c"
#endif
#include "killunsel.c"
#include "mpdcontrol.c"
#include "moveplace.c"
#include "nametag.c"
#include "nomodbuttons.c"
#include "pertag.c"
#include "placemouse.c"
#include "push_no_master.c"
#include "restartsig.c"
#include "riodraw.c"
#include "renamed_scratchpads.c"
#include "shift.c"
#include "shifttag.c"
#include "shiftviewclients.c"
#include "stacker.c"
#include "sticky.c"
#include "swallow.c"
#include "swaptags.c"
#include "switchcol.c"
#include "tab.c"
#include "tagall.c"
#include "tagallmon.c"
#include "tagothermonitor.c"
#include "tagswapmon.c"
#include "togglefullscreen.c"
#include "unfloatvisible.c"
#include "vanitygaps.c"
#include "warp.c"
#include "winview.c"
#include "zoomswap.c"
#include "xrdb.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_columns.c"
#include "layout_deck.c"
#include "layout_fibonacci.c"
#include "layout_gapplessgrid.c"
#include "layout_grid.c"
#include "layout_monocle.c"
#include "layout_nrowgrid.c"
#include "layout_tile.c"

